api:
  url:
    semantic_portal: "http://semantic-portal.net/api/"
jwt:
  token:
    secret: "bohdan"
    expired: "36 000 000"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sptests
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
server:
  port : 8081

