version: '3.1'
services:
  client:
    build: ./../client
    ports:
      - "4200:80"
    container_name: semantic-test-front
    depends_on:
      - server
  server:
    container_name: semantic-tests
    image: semantic-tests
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sptests
