version: '3.1'
services:
  app:
    container_name: semantic-tests
    image: semantic-tests
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sptests
